[browser]
# Disable streamlit collecting user statistics, https://streamlit.io/privacy-policy
gatherUsageStats = false

[client]
# Minimal appearance of user interface
toolbarMode = "minimal"

[theme]
primaryColor = "#9A928F"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e0dedd"
textColor = "#000000"
