[browser]
# Disable streamlit collecting user statistics, https://streamlit.io/privacy-policy
gatherUsageStats = false

[client]
# Minimal appearance of user interface
toolbarMode = "minimal"

[theme]
primaryColor = "#ffc100"
backgroundColor = "#ffc100"
secondaryBackgroundColor = "#ffc100"
textColor = "#ffc100"
